name       : perl-xml-libxml
version    : '2.0209'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0209.tar.gz : b4a5abbcd689aa2fbbc8b7b45339e961c4984e48108494eb6c282b4748222425
homepage   : https://metacpan.org/pod/XML::LibXML
license    : GPL-2.0-or-later
component  : programming.perl
summary    : This module is an interface to libxml2
description: |
    This module is an interface to libxml2, providing XML and HTML parsers with DOM, SAX and XMLReader interfaces, a large subset of DOM Layer 3 interface and a XML::XPath-like interface to XPath API of libxml2
builddeps  :
    - pkgconfig(liblzma)
    - perl-alien-libxml2
    - perl-capture-tiny
    - perl-path-tiny
rundeps    :
    - perl-alien-libxml2
    - perl-file-slurp-tiny
    - perl-xml-saxbase
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
