name       : perl-xml-libxml
version    : 2.0128
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0128.tar.gz : 26e7ba451f3bade4d29ff00653a2ee01d13fe38b9a2ebcd0b0f3f82f9f688f2b
license    : GPL-2.0
component  : programming.perl
summary    : This module is an interface to libxml2
description: |
    This module is an interface to libxml2, providing XML and HTML parsers with DOM, SAX and XMLReader interfaces, a large subset of DOM Layer 3 interface and a XML::XPath-like interface to XPath API of libxml2
rundeps    :
    - perl-file-slurp-tiny
    - perl-xml-saxbase
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
